
# BrieFlow configuration file

# Defining samples:
#   Samples must be defined in the following TSV files with columns:
#     sbs_samples.tsv: sample_fp, well, tile, cycle
#     phenotype_samples.tsv: sample_fp, well, tile

# Paths:
#   Paths are resolved relative to the directory the workflow is run from

# Parameters:
all:
  root_fp: analysis_root/
phenotype:
  align: false
  cell_diameter: 56.32861568936366
  cellprob_threshold: 0
  channel_names:
  - DAPI
  - COXIV
  - CENPA
  - WGA
  cyto_index: 1
  cyto_model: cyto3
  dapi_index: 0
  flow_threshold: 0.4
  foci_channel: 2
  gpu: false
  mode: null
  nuclei_diameter: 11.451797811161432
preprocess:
  phenotype_channel_order: null
  phenotype_channel_order_flip: null
  phenotype_combo_fp: config/phenotype_combo.tsv
  phenotype_round_order: null
  phenotype_samples_fp: config/phenotype_samples.tsv
  sbs_channel_order: null
  sbs_channel_order_flip: null
  sbs_combo_fp: config/sbs_combo.tsv
  sbs_samples_fp: config/sbs_samples.tsv
sbs:
  alignment_method: DAPI
  bases:
  - G
  - T
  - A
  - C
  cell_diameter: 17.805522925178455
  cellprob_threshold: 0
  cyto_index: 4
  cyto_model: cyto3
  dapi_index: 0
  df_design_path: config/pool10_design.tsv
  flow_threshold: 0.4
  gpu: false
  keep_extras: false
  mode: null
  nuclei_diameter: 9.706684619910243
  q_min: 0
  segmentation_cycle_index: 10
  threshold_peaks: 400
