
# BrieFlow configuration file

# Defining samples:
#   Samples must be defined in the following TSV files with columns:
#     sbs_samples.tsv: sample_fp, well, tile, cycle
#     phenotype_samples.tsv: sample_fp, well, tile

# Paths:
#   Paths are resolved relative to the directory the workflow is run from

# Parameters:
all:
  root_fp: analysis_root/
phenotype:
  align: false
  cell_diameter: 53.333077381099564
  cellprob_threshold: 0
  channel_names:
  - DAPI
  - COXIV
  - CENPA
  - WGA
  cyto_index: 1
  cyto_model: cyto3
  dapi_index: 0
  flow_threshold: 0.4
  foci_channel: 2
  gpu: false
  method: cellpose
  mode: null
  nuclei_diameter: 41.97813156768016
  reconcile: contained_in_cells
preprocess:
  phenotype_channel_order: null
  phenotype_channel_order_flip: true
  phenotype_combo_fp: config/phenotype_combo.tsv
  phenotype_round_order: null
  phenotype_samples_fp: config/phenotype_samples.tsv
  sbs_channel_order: null
  sbs_channel_order_flip: true
  sbs_combo_fp: config/sbs_combo.tsv
  sbs_samples_fp: config/sbs_samples.tsv
